# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sa4kyh8xni4f7Py5QSMmpB3CJE9xDapx

### 2. Environment Setup (Google Colab)

First, let's install the necessary Python dependencies.
"""

# Install Python dependencies
!pip install streamlit pytesseract easyocr opencv-python pandas numpy scikit-learn matplotlib seaborn spacy transformers torch pillow

"""Next, we'll install the Tesseract OCR system dependency."""

# Install system dependency for Tesseract OCR
!apt-get install tesseract-ocr -y

"""### 3. Dataset Handling

We'll start by loading the datasets using pandas and performing some initial cleaning. For this example, I'll demonstrate with a placeholder for the dataset. You can replace `your_open_food_facts.csv` and `your_kaggle_fmcg_nutrition.csv` with the actual paths to your datasets.
"""

import pandas as pd
import numpy as np

# --- Dummy Data Generation for Demonstration ---
# In a real scenario, you would replace this with actual data loading.

# Dummy Open Food Facts Data
# Create a dummy DataFrame with relevant columns for cleaning and feature extraction
dummy_food_facts_data = {
    'code': [f'prod_{i:04d}' for i in range(100)],
    'product_name': [f'Product A {i}' if i%2==0 else f'Product B {i}' for i in range(100)],
    'ingredients_text': [f'sugar, salt, water, flavor {i}' if i%3==0 else f'flour, eggs, milk, emulsifier, colorant {i}' for i in range(100)],
    'nutriscore_score': np.random.randint(-5, 40, 100),
    'nutriscore_grade': np.random.choice(['a', 'b', 'c', 'd', 'e'], 100),
    'sugars_100g': np.random.uniform(0, 50, 100),
    'fat_100g': np.random.uniform(0, 30, 100),
    'saturated-fat_100g': np.random.uniform(0, 20, 100),
    'energy_100g': np.random.uniform(100, 2500, 100),
    'proteins_100g': np.random.uniform(0, 20, 100),
    'salt_100g': np.random.uniform(0, 5, 100),
    'additives_n': np.random.randint(0, 5, 100),
    'allergens_en': [None, 'gluten', 'milk', 'nuts', None] * 20
}
df_food_facts = pd.DataFrame(dummy_food_facts_data)
print("Dummy Open Food Facts dataset created.")

# Dummy Kaggle FMCG/Nutrition Data
# Create a dummy DataFrame that might complement the food facts data
dummy_fmcg_nutrition_data = {
    'item_id': [f'FMCG_{i:03d}' for i in range(50)],
    'product_name': [f'Snack {i}' if i%2==0 else f'Beverage {i}' for i in range(50)],
    'sugar_content_g': np.random.uniform(5, 60, 50),
    'fat_content_g': np.random.uniform(1, 40, 50),
    'calorie_per_serving': np.random.uniform(50, 500, 50),
    'contains_additives': np.random.choice([True, False], 50, p=[0.7, 0.3]),
    'ingredient_list': [f'water, sugar, acid, color {i}' if i%4==0 else f'wheat, sugar, oil, salt {i}' for i in range(50)]
}
df_fmcg_nutrition = pd.DataFrame(dummy_fmcg_nutrition_data)
print("Dummy Kaggle FMCG/Nutrition dataset created.")


# Display the first few rows of the loaded datasets (if available)
if not df_food_facts.empty:
    print("\nOpen Food Facts Head:\n", df_food_facts.head())
    print("\nOpen Food Facts Columns:\n", df_food_facts.columns.tolist())

if not df_fmcg_nutrition.empty:
    print("\nKaggle FMCG/Nutrition Head:\n", df_fmcg_nutrition.head())
    print("\nKaggle FMCG/Nutrition Columns:\n", df_fmcg_nutrition.columns.tolist())

"""After loading, the next step is to clean the dataset by handling missing values and normalizing ingredient names. We'll also extract relevant features like sugar, fat, calories, and additives."""

# Placeholder for data cleaning and feature extraction
# This will depend heavily on the actual structure of your datasets.

# Example of how you might start cleaning and extracting features
def clean_and_extract_features(df, source_name):
    if df.empty:
        return pd.DataFrame()

    df_cleaned = df.copy() # Work on a copy to avoid SettingWithCopyWarning

    # Handle missing values (example: fill with 0 or mean/median)
    # For numerical columns, fill with mean or median; for categorical, fill with mode or 'unknown'
    for col in ['sugars_100g', 'fat_100g', 'energy_100g', 'sugar_content_g', 'fat_content_g', 'calorie_per_serving']:
        if col in df_cleaned.columns:
            df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].mean())

    # Normalize ingredient names (example: convert to lowercase)
    # This part will require more sophisticated NLP later
    if 'ingredients_text' in df_cleaned.columns:
        df_cleaned['ingredients_text_normalized'] = df_cleaned['ingredients_text'].astype(str).str.lower().fillna('')
    elif 'ingredient_list' in df_cleaned.columns:
        df_cleaned['ingredients_text_normalized'] = df_cleaned['ingredient_list'].astype(str).str.lower().fillna('')
    else:
        df_cleaned['ingredients_text_normalized'] = ''

    # Extract features (example: assuming columns exist)
    features = pd.DataFrame()

    # Standardize feature names across datasets if possible
    if 'sugars_100g' in df_cleaned.columns:
        features['sugar'] = df_cleaned['sugars_100g']
    elif 'sugar_content_g' in df_cleaned.columns:
        features['sugar'] = df_cleaned['sugar_content_g']
    else:
        features['sugar'] = 0 # Default if column not found

    if 'fat_100g' in df_cleaned.columns:
        features['fat'] = df_cleaned['fat_100g']
    elif 'fat_content_g' in df_cleaned.columns:
        features['fat'] = df_cleaned['fat_content_g']
    else:
        features['fat'] = 0 # Default if column not found

    if 'energy_100g' in df_cleaned.columns:
        features['calories'] = df_cleaned['energy_100g'] # Often energy is in kJ, might need conversion
    elif 'calorie_per_serving' in df_cleaned.columns:
        features['calories'] = df_cleaned['calorie_per_serving']
    else:
        features['calories'] = 0 # Default if column not found

    # For additives, this will be more complex and involve NLP to count/detect
    # For now, a simple placeholder or direct column if available
    if 'additives_n' in df_cleaned.columns:
        features['additive_count'] = df_cleaned['additives_n']
    elif 'contains_additives' in df_cleaned.columns:
        features['additive_count'] = df_cleaned['contains_additives'].astype(int) # Convert boolean to int
    else:
        features['additive_count'] = 0 # Placeholder

    # Ensure all feature columns are numeric
    for col in features.columns:
        features[col] = pd.to_numeric(features[col], errors='coerce').fillna(0)

    print(f"\nCleaned {source_name} Features Head:\n", features.head())
    print(f"Cleaned {source_name} Features Info:\n")
    features.info()
    return features

print("\nCleaning and extracting features from Open Food Facts dataset...")
food_facts_features = clean_and_extract_features(df_food_facts, "Open Food Facts")

print("\nCleaning and extracting features from Kaggle FMCG/Nutrition dataset...")
fmcg_nutrition_features = clean_and_extract_features(df_fmcg_nutrition, "Kaggle FMCG/Nutrition")

"""### 4. Image Processing + OCR

This section will focus on implementing the image processing and OCR capabilities using OpenCV and EasyOCR. We'll start by defining a function to perform OCR on an uploaded image, including preprocessing steps.
"""

import cv2
import easyocr
import numpy as np
from PIL import Image

# Initialize EasyOCR reader (this can take a moment)
# You might need to specify languages, e.g., ['en', 'ne'] for English and Nepali
print("Initializing EasyOCR reader...")
reader = easyocr.Reader(['en'], gpu=False) # Set gpu=True if you have a compatible GPU
print("EasyOCR reader initialized.")

def preprocess_image_for_ocr(image_path):
    """
    Preprocesses an image for better OCR results.
    Args:
        image_path (str): Path to the image file.
    Returns:
        numpy.ndarray: Preprocessed image.
    """
    # Load image using OpenCV
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Image not found at {image_path}")

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply thresholding (Otsu's method)
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # Noise reduction (optional, adjust as needed)
    denoised = cv2.medianBlur(thresh, 3)

    return denoised

def perform_ocr(image_input):
    """
    Performs OCR on an image and returns extracted text.
    Args:
        image_input (Union[str, Image.Image]): Path to image file or PIL Image object.
    Returns:
        str: Concatenated text extracted by OCR.
    """
    if isinstance(image_input, str):
        # Save PIL Image to a temporary file for OpenCV processing
        img_path = image_input
        img_for_ocr = preprocess_image_for_ocr(img_path)
    elif isinstance(image_input, Image.Image):
        # Convert PIL Image to OpenCV format (numpy array)
        img_array = np.array(image_input.convert('RGB'))
        img_cv = img_array[:, :, ::-1].copy() # Convert RGB to BGR

        # Preprocess directly
        gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
        _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        img_for_ocr = cv2.medianBlur(thresh, 3)
    else:
        raise ValueError("image_input must be a file path (str) or a PIL Image object.")

    # EasyOCR expects a path or a numpy array
    result = reader.readtext(img_for_ocr)

    extracted_text = "\n".join([text for (bbox, text, prob) in result])
    return extracted_text

print("OCR functions defined.")

import cv2
import easyocr
import numpy as np
from PIL import Image

# Initialize EasyOCR reader (this can take a moment)
# You might need to specify languages, e.g., ['en', 'ne'] for English and Nepali
print("Initializing EasyOCR reader...")
reader = easyocr.Reader(['en'], gpu=False) # Set gpu=True if you have a compatible GPU
print("EasyOCR reader initialized.")

def preprocess_image_for_ocr(image_path):
    """
    Preprocesses an image for better OCR results.
    Args:
        image_path (str): Path to the image file.
    Returns:
        numpy.ndarray: Preprocessed image.
    """
    # Load image using OpenCV
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Image not found at {image_path}")

    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply thresholding (Otsu's method)
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # Noise reduction (optional, adjust as needed)
    denoised = cv2.medianBlur(thresh, 3)

    return denoised

def perform_ocr(image_input):
    """
    Performs OCR on an image and returns extracted text.
    Args:
        image_input (Union[str, Image.Image]): Path to image file or PIL Image object.
    Returns:
        str: Concatenated text extracted by OCR.
    """
    if isinstance(image_input, str):
        # Save PIL Image to a temporary file for OpenCV processing
        img_path = image_input
        img_for_ocr = preprocess_image_for_ocr(img_path)
    elif isinstance(image_input, Image.Image):
        # Convert PIL Image to OpenCV format (numpy array)
        img_array = np.array(image_input.convert('RGB'))
        img_cv = img_array[:, :, ::-1].copy() # Convert RGB to BGR

        # Preprocess directly
        gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
        _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        img_for_ocr = cv2.medianBlur(thresh, 3)
    else:
        raise ValueError("image_input must be a file path (str) or a PIL Image object.")

    # EasyOCR expects a path or a numpy array
    result = reader.readtext(img_for_ocr)

    extracted_text = "\n".join([text for (bbox, text, prob) in result])
    return extracted_text

print("OCR functions defined.")

"""### 5. NLP Processing

This section will focus on Natural Language Processing (NLP) of the extracted text. We will use spaCy for tokenization, stopword removal, and ingredient normalization. We'll also define a risk dictionary to identify harmful additives, allergens, and sugar-based risks.
"""

import spacy

# Load English tokenizer, tagger, parser, NER and word vectors
# You might need to download the model first: !python -m spacy download en_core_web_sm
print("Loading spaCy model 'en_core_web_sm'...")
try:
    nlp = spacy.load("en_core_web_sm")
    print("spaCy model loaded.")
except OSError:
    print("Downloading spaCy model 'en_core_web_sm'. This may take a moment...")
    !python -m spacy download en_core_web_sm
    nlp = spacy.load("en_core_web_sm")
    print("spaCy model downloaded and loaded.")

# Define a risk dictionary
# This can be expanded based on research and specific requirements
harmful_additives = [
    "aspartame", "msg", "monosodium glutamate", "sodium benzoate",
    "bha", "bht", "sulfites", "nitrates", "nitrites", "high fructose corn syrup"
]
allergens = [
    "gluten", "wheat", "dairy", "milk", "eggs", "soy", "nuts",
    "peanuts", "fish", "shellfish", "sesame", "mustard", "lupin"
]
preservatives = [
    "sodium nitrate", "sodium nitrite", "potassium sorbate", "calcium propionate",
    "bht", "bha", "sulfur dioxide", "benzoic acid"
]
sugar_based_risks = [
    "sugar", "sucrose", "glucose", "fructose", "corn syrup",
    "high fructose corn syrup", "dextrose", "maltose", "lactose"
]

# Combine into a single risk dictionary for easier lookup
risk_dictionary = {
    "harmful": harmful_additives,
    "allergen": allergens,
    "preservative": preservatives,
    "sugar": sugar_based_risks
}

def process_ingredients(text):
    """
    Processes ingredient text using spaCy for tokenization, stopword removal, and normalization.
    Detects harmful additives, allergens, and high sugar content.
    Returns a dictionary with processed text and detected risks.
    """
    doc = nlp(text.lower()) # Process text in lowercase

    # Tokenization and stopword removal
    filtered_tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
    processed_text = " ".join(filtered_tokens)

    detected_risks = {
        "harmful_additives_detected": [],
        "allergens_detected": [],
        "preservatives_detected": [],
        "sugar_indicators_detected": [],
        "total_sugar_indicators": 0
    }

    for token_text in filtered_tokens:
        for risk_type, keywords in risk_dictionary.items():
            if token_text in keywords:
                if risk_type == "harmful" and token_text not in detected_risks["harmful_additives_detected"]:
                    detected_risks["harmful_additives_detected"].append(token_text)
                elif risk_type == "allergen" and token_text not in detected_risks["allergens_detected"]:
                    detected_risks["allergens_detected"].append(token_text)
                elif risk_type == "preservative" and token_text not in detected_risks["preservatives_detected"]:
                    detected_risks["preservatives_detected"].append(token_text)
                elif risk_type == "sugar":
                    if token_text not in detected_risks["sugar_indicators_detected"]:
                        detected_risks["sugar_indicators_detected"].append(token_text)
                    detected_risks["total_sugar_indicators"] += 1

    return {
        "processed_text": processed_text,
        "detected_risks": detected_risks
    }

print("NLP functions and risk dictionary defined.")

import spacy

# Load English tokenizer, tagger, parser, NER and word vectors
# You might need to download the model first: !python -m spacy download en_core_web_sm
print("Loading spaCy model 'en_core_web_sm'...")
try:
    nlp = spacy.load("en_core_web_sm")
    print("spaCy model loaded.")
except OSError:
    print("Downloading spaCy model 'en_core_web_sm'. This may take a moment...")
    !python -m spacy download en_core_web_sm
    nlp = spacy.load("en_core_web_sm")
    print("spaCy model downloaded and loaded.")

# Define a risk dictionary
# This can be expanded based on research and specific requirements
harmful_additives = [
    "aspartame", "msg", "monosodium glutamate", "sodium benzoate",
    "bha", "bht", "sulfites", "nitrates", "nitrites", "high fructose corn syrup"
]
allergens = [
    "gluten", "wheat", "dairy", "milk", "eggs", "soy", "nuts",
    "peanuts", "fish", "shellfish", "sesame", "mustard", "lupin"
]
preservatives = [
    "sodium nitrate", "sodium nitrite", "potassium sorbate", "calcium propionate",
    "bht", "bha", "sulfur dioxide", "benzoic acid"
]
sugar_based_risks = [
    "sugar", "sucrose", "glucose", "fructose", "corn syrup",
    "high fructose corn syrup", "dextrose", "maltose", "lactose"
]

# Combine into a single risk dictionary for easier lookup
risk_dictionary = {
    "harmful": harmful_additives,
    "allergen": allergens,
    "preservative": preservatives,
    "sugar": sugar_based_risks
}

def process_ingredients(text):
    """
    Processes ingredient text using spaCy for tokenization, stopword removal, and normalization.
    Detects harmful additives, allergens, and high sugar content.
    Returns a dictionary with processed text and detected risks.
    """
    doc = nlp(text.lower()) # Process text in lowercase

    # Tokenization and stopword removal
    filtered_tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
    processed_text = " ".join(filtered_tokens)

    detected_risks = {
        "harmful_additives_detected": [],
        "allergens_detected": [],
        "preservatives_detected": [],
        "sugar_indicators_detected": [],
        "total_sugar_indicators": 0
    }

    for token_text in filtered_tokens:
        for risk_type, keywords in risk_dictionary.items():
            if token_text in keywords:
                if risk_type == "harmful" and token_text not in detected_risks["harmful_additives_detected"]:
                    detected_risks["harmful_additives_detected"].append(token_text)
                elif risk_type == "allergen" and token_text not in detected_risks["allergens_detected"]:
                    detected_risks["allergens_detected"].append(token_text)
                elif risk_type == "preservative" and token_text not in detected_risks["preservatives_detected"]:
                    detected_risks["preservatives_detected"].append(token_text)
                elif risk_type == "sugar":
                    if token_text not in detected_risks["sugar_indicators_detected"]:
                        detected_risks["sugar_indicators_detected"].append(token_text)
                    detected_risks["total_sugar_indicators"] += 1

    return {
        "processed_text": processed_text,
        "detected_risks": detected_risks
    }

print("NLP functions and risk dictionary defined.")

"""### 6. Machine Learning Model

Now we will train a simple classifier using the cleaned and extracted numerical features. We'll combine the features from both dummy datasets for this. The model will predict a health risk category (e.g., Healthy, Moderate, Unhealthy).
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Combine features from both dummy datasets
# For simplicity, let's assume these features are for different products
# and we can combine them to form a larger dataset for training.

# Ensure both dataframes have the same columns for concatenation
# If they don't, you might need to align them or fill missing columns with zeros
combined_features = pd.concat([food_facts_features, fmcg_nutrition_features], ignore_index=True)

# For demonstration, let's create a dummy target variable (health risk category)
# In a real scenario, this would come from your dataset (e.g., Nutri-Score grades mapped to risk)

# Let's define simple thresholds for creating a target variable for classification
# This is a placeholder and should be refined with domain knowledge or actual labels
def create_dummy_health_label(row):
    sugar_risk = 0.4 * (row['sugar'] / 100) # Assuming sugar_100g max is 100
    fat_risk = 0.3 * (row['fat'] / 100) # Assuming fat_100g max is 100
    additive_risk = 0.3 * (row['additive_count'] / 5) # Assuming max 5 additives

    total_risk = sugar_risk + fat_risk + additive_risk

    if total_risk < 0.2:
        return 'Healthy'
    elif total_risk < 0.5:
        return 'Moderate'
    else:
        return 'Unhealthy'

combined_features['health_label'] = combined_features.apply(create_dummy_health_label, axis=1)

X = combined_features[['sugar', 'fat', 'calories', 'additive_count']]
y = combined_features['health_label']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Health Label Distribution in Training Set:\n", y_train.value_counts())

# Initialize and train a Random Forest Classifier
print("\nTraining Random Forest Classifier...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
print("Random Forest Classifier trained.")

# Evaluate the model
y_pred = model.predict(X_test)
print("\nModel Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import pandas as pd # Ensure pandas is imported if not already
import numpy as np # Ensure numpy is imported if not already

# Combine features from both dummy datasets
# For simplicity, let's assume these features are for different products
# and we can combine them to form a larger dataset for training.

# Ensure both dataframes have the same columns for concatenation
# If they don't, you might need to align them or fill missing columns with zeros
combined_features = pd.concat([food_facts_features, fmcg_nutrition_features], ignore_index=True)

# For demonstration, let's create a dummy target variable (health risk category)
# In a real scenario, this would come from your dataset (e.g., Nutri-Score grades mapped to risk)

# Let's define simple thresholds for creating a target variable for classification
# This is a placeholder and should be refined with domain knowledge or actual labels
def create_dummy_health_label(row):
    sugar_risk = 0.4 * (row['sugar'] / 100) # Assuming sugar_100g max is 100
    fat_risk = 0.3 * (row['fat'] / 100) # Assuming fat_100g max is 100
    additive_risk = 0.3 * (row['additive_count'] / 5) # Assuming max 5 additives

    total_risk = sugar_risk + fat_risk + additive_risk

    if total_risk < 0.2:
        return 'Healthy'
    elif total_risk < 0.5:
        return 'Moderate'
    else:
        return 'Unhealthy'

combined_features['health_label'] = combined_features.apply(create_dummy_health_label, axis=1)

X = combined_features[['sugar', 'fat', 'calories', 'additive_count']]
y = combined_features['health_label']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Health Label Distribution in Training Set:\n", y_train.value_counts())

# Initialize and train a Random Forest Classifier
print("\nTraining Random Forest Classifier...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
print("Random Forest Classifier trained.")

# Evaluate the model
y_pred = model.predict(X_test)
print("\nModel Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# --- 6.1 Feature Engineering from NLP Output ---

# Apply the NLP processing function to the ingredient texts of the combined features
# First, create a placeholder for ingredient texts if not already present in combined_features
# We need to reconstruct the ingredients text for combined_features from the original DFs

# Create a mapping from product code/id to ingredients text
food_facts_ingredients = df_food_facts[['code', 'ingredients_text']].set_index('code')
fmcg_nutrition_ingredients = df_fmcg_nutrition[['item_id', 'ingredient_list']].set_index('item_id')

# Let's create a combined ingredients series matching the combined_features index
# This assumes the combined_features index directly corresponds to the order of original DFs
# A more robust way would be to merge based on original identifiers if they were preserved.

# For simplicity given the dummy data concatenation, we'll recreate the combined ingredients
all_ingredients_text_food_facts = df_food_facts['ingredients_text'].fillna('')
all_ingredients_text_fmcg = df_fmcg_nutrition['ingredient_list'].fillna('')

combined_ingredients_series = pd.concat([all_ingredients_text_food_facts, all_ingredients_text_fmcg], ignore_index=True)

# Apply NLP processing
print("\nApplying NLP processing to combined ingredients...")
nlp_results = combined_ingredients_series.apply(process_ingredients)

# Extract NLP-derived features
combined_features['num_harmful_additives'] = nlp_results.apply(lambda x: len(x['detected_risks']['harmful_additives_detected']))
combined_features['num_allergens'] = nlp_results.apply(lambda x: len(x['detected_risks']['allergens_detected']))
combined_features['num_preservatives'] = nlp_results.apply(lambda x: len(x['detected_risks']['preservatives_detected']))
combined_features['total_sugar_indicators_nlp'] = nlp_results.apply(lambda x: x['detected_risks']['total_sugar_indicators'])

print("NLP-derived features added to combined_features.")
print(combined_features[['sugar', 'fat', 'calories', 'additive_count', 'num_harmful_additives', 'num_allergens', 'num_preservatives', 'total_sugar_indicators_nlp', 'health_label']].head())

# --- 6.2 Retrain ML Model with Enhanced Features ---

# Define new feature set X including NLP features
X_enhanced = combined_features[['sugar', 'fat', 'calories', 'additive_count',
                                'num_harmful_additives', 'num_allergens',
                                'num_preservatives', 'total_sugar_indicators_nlp']]
y = combined_features['health_label']

# Split data into training and testing sets
X_train_enhanced, X_test_enhanced, y_train, y_test = train_test_split(X_enhanced, y, test_size=0.2, random_state=42, stratify=y)

print("\nShape of X_train_enhanced:", X_train_enhanced.shape)
print("Health Label Distribution in Training Set (Enhanced):\n", y_train.value_counts())

# Initialize and train a new Random Forest Classifier with enhanced features
print("\nTraining Random Forest Classifier with enhanced features...")
model_enhanced = RandomForestClassifier(n_estimators=100, random_state=42)
model_enhanced.fit(X_train_enhanced, y_train)
print("Random Forest Classifier with enhanced features trained.")

# Evaluate the enhanced model
y_pred_enhanced = model_enhanced.predict(X_test_enhanced)
print("\nModel Evaluation with Enhanced Features:")
print("Accuracy:", accuracy_score(y_test, y_pred_enhanced))
print("\nClassification Report (Enhanced):\n", classification_report(y_test, y_pred_enhanced))

# Display feature importances
print("\nFeature Importances (Enhanced Model):")
feature_importances = pd.Series(model_enhanced.feature_importances_, index=X_enhanced.columns)
print(feature_importances.sort_values(ascending=False))

"""### 7. Health Scoring System

Now, let's create a health scoring system based on the NLP-derived features and the predictions from our machine learning model. This system will interpret the model's output and present a more human-readable health assessment.
"""

def get_health_score(sugar, fat, calories, additive_count, num_harmful_additives, num_allergens, num_preservatives, total_sugar_indicators_nlp, ml_prediction):
    """
    Calculates a health score based on various features and ML prediction.
    A lower score indicates a healthier product.
    """
    score = 0

    # Base score from numerical features (example weights)
    score += sugar * 0.5
    score += fat * 0.4
    score += calories * 0.05
    score += additive_count * 5 # Penalize based on count

    # Add penalties for NLP-derived risks
    score += num_harmful_additives * 20 # High penalty for harmful additives
    score += num_allergens * 10       # Moderate penalty for allergens
    score += num_preservatives * 8    # Penalty for preservatives
    score += total_sugar_indicators_nlp * 3 # Penalty for various sugar forms

    # Adjust score based on ML prediction
    if ml_prediction == 'Unhealthy':
        score += 50
    elif ml_prediction == 'Moderate':
        score += 20
    # 'Healthy' will have no additional penalty

    return round(score, 2)

def get_health_label_from_score(score):
    """
    Converts a numerical health score into a categorical health label.
    """
    if score < 50:
        return 'Very Healthy'
    elif score < 150:
        return 'Healthy'
    elif score < 300:
        return 'Moderate Risk'
    else:
        return 'High Risk'

print("Health scoring system functions defined.")

"""### 8. Streamlit UI

Now, let's integrate all the components into a user-friendly Streamlit interface. This will allow users to upload an image of a product label, get OCR results, NLP analysis, and a health score prediction.

First, we'll create the `streamlit_app.py` file with the basic structure and the image upload functionality.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import cv2
# import easyocr
# from PIL import Image
# import spacy
# from sklearn.ensemble import RandomForestClassifier
# import io # Import io for BytesIO
# 
# # --- 1. Global Variables and Initializations (Copy from previous cells) ---
# # Initialize EasyOCR reader
# @st.cache_resource
# def get_easyocr_reader():
#     return easyocr.Reader(['en'], gpu=False)
# reader = get_easyocr_reader()
# 
# # Load spaCy model
# @st.cache_resource
# def get_spacy_nlp():
#     try:
#         nlp_model = spacy.load("en_core_web_sm")
#     except OSError:
#         # This part should ideally be handled during environment setup in Colab
#         # For Streamlit, ensure the model is already downloaded or handle download silently
#         # For now, assuming it's available or handled by initial Colab setup
#         st.error("spaCy model 'en_core_web_sm' not found. Please ensure it's downloaded in your Colab environment.")
#         st.stop()
#     return nlp_model
# nlp = get_spacy_nlp()
# 
# # Risk Dictionary (Copy from previous cells)
# harmful_additives = [
#     "aspartame", "msg", "monosodium glutamate", "sodium benzoate",
#     "bha", "bht", "sulfites", "nitrates", "nitrites", "high fructose corn syrup"
# ]
# allergens = [
#     "gluten", "wheat", "dairy", "milk", "eggs", "soy", "nuts",
#     "peanuts", "fish", "shellfish", "sesame", "mustard", "lupin"
# ]
# preservatives = [
#     "sodium nitrate", "sodium nitrite", "potassium sorbate", "calcium propionate",
#     "bht", "bha", "sulfur dioxide", "benzoic acid"
# ]
# sugar_based_risks = [
#     "sugar", "sucrose", "glucose", "fructose", "corn syrup",
#     "high fructose corn syrup", "dextrose", "maltose", "lactose"
# ]
# risk_dictionary = {
#     "harmful": harmful_additives,
#     "allergen": allergens,
#     "preservative": preservatives,
#     "sugar": sugar_based_risks
# }
# 
# # --- 2. Functions (Copy and adapt from previous cells) ---
# 
# def preprocess_image_for_ocr(image_bytes):
#     """
#     Preprocesses an image for better OCR results from bytes.
#     """
#     # Convert bytes to numpy array
#     nparr = np.frombuffer(image_bytes, np.uint8)
#     img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
# 
#     if img is None:
#         st.error("Could not decode image.")
#         return None
# 
#     gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#     _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
#     denoised = cv2.medianBlur(thresh, 3)
#     return denoised
# 
# def perform_ocr(image_input_bytes):
#     """
#     Performs OCR on image bytes and returns extracted text.
#     """
#     img_for_ocr = preprocess_image_for_ocr(image_input_bytes)
#     if img_for_ocr is None:
#         return ""
# 
#     result = reader.readtext(img_for_ocr)
#     extracted_text = "\n".join([text for (bbox, text, prob) in result])
#     return extracted_text
# 
# def process_ingredients(text):
#     """
#     Processes ingredient text using spaCy and detects risks.
#     """
#     doc = nlp(text.lower())
#     filtered_tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
#     processed_text = " ".join(filtered_tokens)
# 
#     detected_risks = {
#         "harmful_additives_detected": [],
#         "allergens_detected": [],
#         "preservatives_detected": [],
#         "sugar_indicators_detected": [],
#         "total_sugar_indicators": 0
#     }
# 
#     for token_text in filtered_tokens:
#         for risk_type, keywords in risk_dictionary.items():
#             if token_text in keywords:
#                 if risk_type == "harmful" and token_text not in detected_risks["harmful_additives_detected"]:
#                     detected_risks["harmful_additives_detected"].append(token_text)
#                 elif risk_type == "allergen" and token_text not in detected_risks["allergens_detected"]:
#                     detected_risks["allergens_detected"].append(token_text)
#                 elif risk_type == "preservative" and token_text not in detected_risks["preservatives_detected"]:
#                     detected_risks["preservatives_detected"].append(token_text)
#                 elif risk_type == "sugar":
#                     if token_text not in detected_risks["sugar_indicators_detected"]:
#                         detected_risks["sugar_indicators_detected"].append(token_text)
#                     detected_risks["total_sugar_indicators"] += 1
# 
#     return {
#         "processed_text": processed_text,
#         "detected_risks": detected_risks
#     }
# 
# def get_health_score(sugar, fat, calories, additive_count, num_harmful_additives, num_allergens, num_preservatives, total_sugar_indicators_nlp, ml_prediction):
#     """
#     Calculates a health score based on various features and ML prediction.
#     A lower score indicates a healthier product.
#     """
#     score = 0
#     score += sugar * 0.5
#     score += fat * 0.4
#     score += calories * 0.05
#     score += additive_count * 5
#     score += num_harmful_additives * 20
#     score += num_allergens * 10
#     score += num_preservatives * 8
#     score += total_sugar_indicators_nlp * 3
# 
#     if ml_prediction == 'Unhealthy':
#         score += 50
#     elif ml_prediction == 'Moderate':
#         score += 20
# 
#     return round(score, 2)
# 
# def get_health_label_from_score(score):
#     """
#     Converts a numerical health score into a categorical health label.
#     """
#     if score < 50:
#         return 'Very Healthy'
#     elif score < 150:
#         return 'Healthy'
#     elif score < 300:
#         return 'Moderate Risk'
#     else:
#         return 'High Risk'
# 
# # --- 3. Streamlit UI ---
# st.title("e-K Cha Label? 🇳🇵")
# st.markdown("### Analyze your FMCG Product Label!")
# 
# st.write("Upload an image of a food product label to get a health analysis.")
# 
# uploaded_file = st.file_uploader("Choose an image file", type=["png", "jpg", "jpeg"])
# 
# if uploaded_file is not None:
#     image_bytes = uploaded_file.read()
#     image = Image.open(io.BytesIO(image_bytes))
#     st.image(image, caption='Uploaded Label Image', use_column_width=True)
#     st.write("")
#     st.write("Processing image...")
# 
#     # Perform OCR
#     ocr_text = perform_ocr(image_bytes)
#     st.subheader("Extracted Text (OCR):")
#     st.write(ocr_text)
# 
#     if ocr_text:
#         st.write("Performing NLP analysis...")
#         nlp_analysis = process_ingredients(ocr_text)
#         st.subheader("NLP Analysis:")
#         st.json(nlp_analysis['detected_risks'])
# 
#         # Placeholder for ML prediction and health score (will integrate actual model next)
#         # For now, we'll use dummy features derived from NLP results to demonstrate scoring
#         # In a real app, you'd extract numerical features from OCR/NLP for the ML model
# 
#         # Dummy numerical features for demonstration with health scoring
#         # In a real scenario, these would be parsed more rigorously from OCR text
#         dummy_sugar = ocr_text.lower().count('sugar') * 10 # Example heuristic
#         dummy_fat = ocr_text.lower().count('fat') * 5    # Example heuristic
#         dummy_calories = ocr_text.lower().count('calorie') * 50 # Example heuristic
#         dummy_additive_count = len(nlp_analysis['detected_risks']['harmful_additives_detected']) + \
#                                len(nlp_analysis['detected_risks']['preservatives_detected'])
# 
#         num_harmful_additives = len(nlp_analysis['detected_risks']['harmful_additives_detected'])
#         num_allergens = len(nlp_analysis['detected_risks']['allergens_detected'])
#         num_preservatives = len(nlp_analysis['detected_risks']['preservatives_detected'])
#         total_sugar_indicators_nlp = nlp_analysis['detected_risks']['total_sugar_indicators']
# 
#         # Dummy ML prediction for now (will integrate the actual trained model)
#         dummy_ml_prediction = 'Moderate' # Default to moderate for demo
# 
#         health_score = get_health_score(
#             dummy_sugar, dummy_fat, dummy_calories, dummy_additive_count,
#             num_harmful_additives, num_allergens, num_preservatives, total_sugar_indicators_nlp,
#             dummy_ml_prediction
#         )
#         health_label = get_health_label_from_score(health_score)
# 
#         st.subheader("Health Analysis:")
#         st.metric(label="Overall Health Score", value=health_score)
#         st.metric(label="Health Label", value=health_label)
# 
#     else:
#         st.warning("No text extracted. Please try another image or ensure text is clear.")
# 
# # --- 4. Running Streamlit in Colab (Instructions) ---
# # To run this Streamlit app, save this code into a file named `streamlit_app.py`
# # and then execute the following commands in new Colab cells:
# #
# # !npm install localtunnel
# # !streamlit run streamlit_app.py &>/dev/null&  npx localtunnel --port 8501

# Install localtunnel to expose the Streamlit app
!npm install localtunnel

# Run the Streamlit app and expose it via localtunnel
!streamlit run streamlit_app.py &>/dev/null&  npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pytesseract
# easyocr
# opencv-python
# pandas
# numpy
# scikit-learn
# matplotlib
# seaborn
# spacy
# transformers
# torch
# pillow
# # If you've downloaded the spaCy model explicitly, you might need to add this:
# # en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
#

"""Now you have `requirements.txt` generated. Here's a recap of the steps to deploy to Streamlit Cloud:

1.  **Create a GitHub Repository:** Make a new public or private repository on GitHub.
2.  **Upload Files:** Upload both `streamlit_app.py` and the newly created `requirements.txt` to your GitHub repository.
3.  **Go to Streamlit Cloud:** Visit [share.streamlit.io](https://share.streamlit.io/).
4.  **Connect to GitHub:** Sign in with your GitHub account.
5.  **Deploy a New App:** Click on 'New app' and select your GitHub repository, the branch (usually `main`), and specify the file path to `streamlit_app.py` (e.g., `streamlit_app.py`).
6.  **Deploy:** Click the 'Deploy!' button. Streamlit Cloud will handle the rest, and you'll get a permanent public URL for your app.

Let me know if you encounter any issues during the deployment process!
"""